#!/bin/bash
#
# Cline CLI Refactoring Analysis Script
# Identifies refactoring opportunities and suggests improvements
# Usage: ./scripts/cline/refactor-analysis.sh [--path <directory>]
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
CLINE_ENABLED="${CLINE_ENABLED:-true}"
OUTPUT_FILE="$PROJECT_ROOT/docs/REFACTORING_OPPORTUNITIES.md"

# Check if Cline is enabled
if [ "$CLINE_ENABLED" != "true" ]; then
    echo -e "${YELLOW}⚠ Cline is disabled${NC}"
    exit 0
fi

# Check if Cline CLI is installed
if ! command -v cline &> /dev/null; then
    echo -e "${RED}✗ Cline CLI not found${NC}"
    exit 1
fi

# Parse arguments
TARGET_PATH="$PROJECT_ROOT"
if [ "$1" = "--path" ] && [ -n "$2" ]; then
    TARGET_PATH="$2"
fi

echo -e "${BLUE}🔍 Analyzing code for refactoring opportunities...${NC}"
echo -e "${BLUE}Path: $TARGET_PATH${NC}"

cd "$PROJECT_ROOT"

# Initialize report
cat > "$OUTPUT_FILE" << 'EOF'
# Refactoring Opportunities

Generated by Cline CLI

## Summary

This report identifies code smells, duplication, and refactoring opportunities.

---

EOF

# Analyze different aspects

# 1. Code Duplication
echo -e "\n${BLUE}📊 Checking for code duplication...${NC}"
cline analyze-duplication \
    --path "$TARGET_PATH" \
    --threshold 5 \
    --output "$OUTPUT_FILE" \
    --append

# 2. Complexity Analysis
echo -e "\n${BLUE}📊 Analyzing code complexity...${NC}"
cline analyze-complexity \
    --path "$TARGET_PATH" \
    --threshold 10 \
    --output "$OUTPUT_FILE" \
    --append

# 3. Type Safety Issues
echo -e "\n${BLUE}📊 Checking type safety...${NC}"
cline analyze-types \
    --path "$TARGET_PATH" \
    --strict-mode \
    --output "$OUTPUT_FILE" \
    --append

# 4. Performance Issues
echo -e "\n${BLUE}📊 Identifying performance issues...${NC}"
cline analyze-performance \
    --path "$TARGET_PATH" \
    --context "React 19, Next.js 16, Fastify 5" \
    --output "$OUTPUT_FILE" \
    --append

# 5. Security Concerns
echo -e "\n${BLUE}📊 Scanning for security issues...${NC}"
cline analyze-security \
    --path "$TARGET_PATH" \
    --output "$OUTPUT_FILE" \
    --append

# 6. Best Practices
echo -e "\n${BLUE}📊 Checking best practices...${NC}"
cline analyze-best-practices \
    --path "$TARGET_PATH" \
    --framework "nextjs,fastify,supabase" \
    --output "$OUTPUT_FILE" \
    --append

# 7. API Design Analysis (for backend)
if [[ "$TARGET_PATH" =~ apps/api ]]; then
    echo -e "\n${BLUE}📊 Analyzing API design...${NC}"
    cline analyze-api-design \
        --path "$TARGET_PATH" \
        --standard "REST" \
        --output "$OUTPUT_FILE" \
        --append
fi

# 8. Component Structure (for frontend)
if [[ "$TARGET_PATH" =~ apps/web ]]; then
    echo -e "\n${BLUE}📊 Analyzing component structure...${NC}"
    cline analyze-components \
        --path "$TARGET_PATH" \
        --framework "react" \
        --output "$OUTPUT_FILE" \
        --append
fi

# Generate priority recommendations
echo -e "\n${BLUE}📊 Generating priority recommendations...${NC}"

cat >> "$OUTPUT_FILE" << 'EOF'

---

## Priority Recommendations

Based on the analysis above, here are the top refactoring priorities:

EOF

cline prioritize-refactoring \
    --input "$OUTPUT_FILE" \
    --output "$OUTPUT_FILE" \
    --append

# Format the output
if command -v prettier &> /dev/null; then
    prettier --write "$OUTPUT_FILE" > /dev/null 2>&1
fi

# Display summary
echo -e "\n${GREEN}✓ Analysis complete${NC}"
echo -e "${BLUE}Report saved to: $OUTPUT_FILE${NC}"

# Show quick summary
echo -e "\n${BLUE}Quick Summary:${NC}"
if command -v head &> /dev/null && command -v tail &> /dev/null; then
    head -n 50 "$OUTPUT_FILE" | tail -n 30
fi

# Open in editor if available
if [ -n "$EDITOR" ]; then
    echo -e "\n${YELLOW}Open report in editor? (y/N)${NC}"
    read -p "" -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        $EDITOR "$OUTPUT_FILE"
    fi
fi

echo -e "\n${YELLOW}Next steps:${NC}"
echo "  1. Review the report: $OUTPUT_FILE"
echo "  2. Prioritize refactoring tasks"
echo "  3. Create GitHub issues for high-priority items"
echo "  4. Update backlog in project board"
